# Generated by Django 6.1.2 on 2026-10-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autor_categoria_alter_livro_autor_livro_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='biblioteca.categoria'),
        ),
    ]
