# Generated by Django 6.1.2 on 2026-10-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_livro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(related_name='livros', to='biblioteca.autor'),
        ),
    ]
