# Generated by Django 6.1.2 on 2026-10-09 17:53

from django.db import migrations, transaction

transaction

def autor_to_atores(apps, schema_editor):
    Livro = apps.get_model('biblioteca', 'Livro')

    with transaction.atomic():
        for livro in Livro.objects.all():
            if livro.autor:
                livro.autores.add(livro.autor)

def reverse_autor_to_atores(apps, schema_editor):
    Livro = apps.get_model('biblioteca', 'Livro')

    with transaction.atomic():
        for livro in Livro.objects.all():
            if livro.autores.exists():
                livro.autores.remove(livro.autor)
                livro.autor = livro.autores.first()


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_livro_autores'),
    ]

    operations = [
        migrations.RunPython(autor_to_atores, reverse_autor_to_atores),
    ]
