# Generated by Django 6.1.2 on 2026-10-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_ator_to_atores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
    ]
